import os
import shutil
import tempfile
import logging
from typing import List, Dict, Any, Optional

logger = logging.getLogger(__name__)

class StyloWrapper:
    """
    Python wrapper for the R 'stylo' package.
    Provides advanced stylometric analysis using Burrows' Delta.
    """

    def __init__(self):
        self.r_available = False
        self.stylo_available = False
        self._check_environment()

    def _check_environment(self):
        """Checks if R, rpy2, and the stylo package are installed."""
        try:
            import rpy2.robjects as robjects
            from rpy2.robjects.packages import importr, isinstalled
            
            # Check for R version
            r_version = robjects.r['version']
            self.r_available = True
            
            # Check for stylo package
            if isinstalled('stylo'):
                self.stylo_available = True
                logger.info("✅ R and 'stylo' package detected.")
            else:
                logger.warning("⚠️ R 'stylo' package is NOT installed.")
                
        except ImportError:
            logger.warning("⚠️ 'rpy2' is NOT installed. Run: pip install rpy2")
        except Exception as e:
            logger.warning(f"⚠️ R environment error: {e}")

    def get_status(self) -> Dict[str, bool]:
        """Returns the readiness status of the R environment."""
        return {
            "r_available": self.r_available,
            "stylo_available": self.stylo_available,
            "ready": self.r_available and self.stylo_available
        }

    def analyze_distance(self, target_text: str, corpus_folder: str) -> List[Dict[str, Any]]:
        """
        Performs Delta analysis on target_text using the referenced corpus.
        
        Args:
            target_text: The text to be attributed.
            corpus_folder: Folder containing known author texts.
            
        Returns:
            Ranked list of authors and their distance scores.
        """
        if not self.r_available or not self.stylo_available:
            raise RuntimeError("R Stylo environment is not configured. Please install R, stylo, and rpy2.")

        if not os.path.exists(corpus_folder):
            raise FileNotFoundError(f"Corpus folder not found: {corpus_folder}")

        # Create temporary working directory
        with tempfile.TemporaryDirectory() as temp_dir:
            # Stylo expects specific folder structure: 'primary_set' for test, 'secondary_set' for training
            primary_dir = os.path.join(temp_dir, "primary_set")
            secondary_dir = os.path.join(temp_dir, "secondary_set")
            os.makedirs(primary_dir)
            os.makedirs(secondary_dir)

            # Write target text to primary set
            with open(os.path.join(primary_dir, "unknown_text.txt"), "w", encoding="utf-8") as f:
                f.write(target_text)

            # Link/Copy corpus to secondary set
            for file in os.listdir(corpus_folder):
                shutil.copy(os.path.join(corpus_folder, file), secondary_dir)

            try:
                from rpy2.robjects.packages import importr
                stylo_api = importr('stylo')
                
                # Call stylo in batch mode
                # working.directory is where stylo reads/writes its files
                stylo_api.stylo(
                    gui=False,
                    analysis_type="Delta",
                    working_directory=temp_dir,
                    display_on_screen=False,
                    save_distance_table=True
                )

                # Parse distance_table.txt
                # Format is usually a square matrix or a ranked list depending on settings
                # We look for 'distance_table.txt' in the temp_dir
                dist_file = os.path.join(temp_dir, "distance_table.txt")
                if not os.path.exists(dist_file):
                    # Sometimes stylo puts things in a sub-folder based on analysis
                    dist_file = os.path.join(temp_dir, "unknown_text_dist_table.txt") # Example variations

                results = self._parse_distances(temp_dir)
                return results

            except Exception as e:
                logger.error(f"❌ Stylo analysis failed: {e}")
                raise

    def _parse_distances(self, temp_dir: str) -> List[Dict[str, Any]]:
        """Parses the results generated by stylo."""
        # This is a simplified parser intended to find the closest author in secondary_set
        # A more robust version would handle multiple tables
        results = []
        # Logic to read distance_table.txt or equivalent and return sorted results
        # For prototype, we verify if the file was created.
        logger.info(f"Parsing results in {temp_dir}")
        return [{"author": "demo", "distance": 0.0}] # Placeholder for actual parsing logic
