import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any

from src.core.plugin_base import BasePlugin

logger = logging.getLogger("LawnmowerMan.ExportFormats")

EXPORTS_DIR = Path(__file__).parent / "exports"


class ExportFormatter:
    def __init__(self):
        self.templates = {}
        self._load_templates()

    def _load_templates(self):
        default_template = {
            "name": "Default",
            "header": "Forensic Analysis Report",
            "footer": "Generated by SME v3.0.1",
            "branding": True,
        }
        self.templates["default"] = default_template

    def export_to_pdf(self, data: dict, template: str = "default") -> str:
        """Export report to PDF format."""
        try:
            from reportlab.lib import colors
            from reportlab.lib.pagesizes import letter
            from reportlab.lib.styles import getSampleStyleSheet
            from reportlab.lib.units import inch
            from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

            EXPORTS_DIR.mkdir(parents=True, exist_ok=True)
            filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
            filepath = EXPORTS_DIR / filename

            doc = SimpleDocTemplate(str(filepath), pagesize=letter)
            story = []
            styles = getSampleStyleSheet()

            tmpl = self.templates.get(template, self.templates["default"])
            if tmpl.get("branding"):
                story.append(Paragraph(tmpl["header"], styles["Title"]))
                story.append(Spacer(1, 0.5 * inch))

            story.append(
                Paragraph(
                    f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles["Normal"]
                )
            )
            story.append(Spacer(1, 0.3 * inch))

            if "title" in data:
                story.append(Paragraph(data["title"], styles["Heading1"]))

            if "summary" in data:
                story.append(Paragraph("Summary", styles["Heading2"]))
                story.append(Paragraph(data["summary"], styles["Normal"]))
                story.append(Spacer(1, 0.3 * inch))

            if "findings" in data and isinstance(data["findings"], list):
                story.append(Paragraph("Findings", styles["Heading2"]))
                for finding in data["findings"]:
                    story.append(Paragraph(f"• {finding}", styles["Normal"]))
                story.append(Spacer(1, 0.3 * inch))

            if "metadata" in data and isinstance(data["metadata"], dict):
                story.append(Paragraph("Metadata", styles["Heading2"]))
                meta_data = [[k, str(v)] for k, v in data["metadata"].items()]
                t = Table(meta_data, colWidths=[2 * inch, 4 * inch])
                t.setStyle(
                    TableStyle(
                        [
                            ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
                            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                            ("FONTSIZE", (0, 0), (-1, -1), 10),
                        ]
                    )
                )
                story.append(t)

            if tmpl.get("footer"):
                story.append(Spacer(1, 0.5 * inch))
                story.append(Paragraph(tmpl["footer"], styles["Normal"]))

            doc.build(story)
            logger.info(f"Exported PDF: {filename}")
            return str(filepath)
        except ImportError:
            logger.warning("reportlab not installed, falling back to text export")
            return self.export_to_text(data)
        except Exception as e:
            logger.exception(f"PDF export failed: {e}")
            return ""

    def export_to_docx(self, data: dict, template: str = "default") -> str:
        """Export report to Word DOCX format."""
        try:
            from docx import Document
            from docx.enum.text import WD_ALIGN_PARAGRAPH
            from docx.shared import Inches, Pt

            EXPORTS_DIR.mkdir(parents=True, exist_ok=True)
            filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
            filepath = EXPORTS_DIR / filename

            doc = Document()
            tmpl = self.templates.get(template, self.templates["default"])

            if tmpl.get("branding"):
                title = doc.add_heading(tmpl["header"], 0)
                title.alignment = WD_ALIGN_PARAGRAPH.CENTER

            doc.add_paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

            if "title" in data:
                doc.add_heading(data["title"], 1)

            if "summary" in data:
                doc.add_heading("Summary", 2)
                doc.add_paragraph(data["summary"])

            if "findings" in data and isinstance(data["findings"], list):
                doc.add_heading("Findings", 2)
                for finding in data["findings"]:
                    doc.add_paragraph(f"• {finding}")

            if "metadata" in data and isinstance(data["metadata"], dict):
                doc.add_heading("Metadata", 2)
                table = doc.add_table(rows=len(data["metadata"]) + 1, cols=2)
                table.style = "Table Grid"
                header_row = table.rows[0]
                header_row.cells[0].text = "Key"
                header_row.cells[1].text = "Value"
                for i, (key, value) in enumerate(data["metadata"].items()):
                    row = table.rows[i + 1]
                    row.cells[0].text = key
                    row.cells[1].text = str(value)

            if tmpl.get("footer"):
                doc.add_paragraph(tmpl["footer"]).alignment = WD_ALIGN_PARAGRAPH.CENTER

            doc.save(str(filepath))
            logger.info(f"Exported DOCX: {filename}")
            return str(filepath)
        except ImportError:
            logger.warning("python-docx not installed, falling back to text export")
            return self.export_to_text(data)
        except Exception as e:
            logger.exception(f"DOCX export failed: {e}")
            return ""

    def export_to_html(self, data: dict, template: str = "default") -> str:
        """Export report to HTML format."""
        EXPORTS_DIR.mkdir(parents=True, exist_ok=True)
        filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        filepath = EXPORTS_DIR / filename

        tmpl = self.templates.get(template, self.templates["default"])

        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{data.get("title", "Forensic Report")}</title>
    <style>
        body {{ font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #1f2937; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }}
        h2 {{ color: #374151; margin-top: 30px; }}
        .meta {{ background: #f3f4f6; padding: 15px; border-radius: 5px; margin: 20px 0; }}
        .finding {{ margin: 10px 0; padding: 10px; background: #f9fafb; border-left: 3px solid #3b82f6; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; }}
    </style>
</head>
<body>
    <h1>{tmpl.get("header", "Forensic Report")}</h1>
    <p>Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
"""

        if "title" in data:
            html += f"    <h1>{data['title']}</h1>\n"

        if "summary" in data:
            html += f"    <h2>Summary</h2>\n    <p>{data['summary']}</p>\n"

        if "findings" in data and isinstance(data["findings"], list):
            html += "    <h2>Findings</h2>\n"
            for finding in data["findings"]:
                html += f"    <div class='finding'>{finding}</div>\n"

        if "metadata" in data and isinstance(data["metadata"], dict):
            html += "    <h2>Metadata</h2>\n    <div class='meta'>\n    <table>\n"
            for key, value in data["metadata"].items():
                html += f"      <tr><td><strong>{key}:</strong></td><td>{value}</td></tr>\n"
            html += "    </table>\n    </div>\n"

        if tmpl.get("footer"):
            html += f"    <div class='footer'>{tmpl['footer']}</div>\n"

        html += "</body>\n</html>"

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html)

        logger.info(f"Exported HTML: {filename}")
        return str(filepath)

    def export_to_markdown(self, data: dict, template: str = "default") -> str:
        """Export report to Markdown format."""
        EXPORTS_DIR.mkdir(parents=True, exist_ok=True)
        filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        filepath = EXPORTS_DIR / filename

        tmpl = self.templates.get(template, self.templates["default"])

        md = f"# {tmpl.get('header', 'Forensic Report')}\n\n"
        md += f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n\n"

        if "title" in data:
            md += f"# {data['title']}\n\n"

        if "summary" in data:
            md += "## Summary\n\n"
            md += f"{data['summary']}\n\n"

        if "findings" in data and isinstance(data["findings"], list):
            md += "## Findings\n\n"
            for finding in data["findings"]:
                md += f"- {finding}\n"
            md += "\n"

        if "metadata" in data and isinstance(data["metadata"], dict):
            md += "## Metadata\n\n"
            for key, value in data["metadata"].items():
                md += f"- **{key}**: {value}\n"
            md += "\n"

        if tmpl.get("footer"):
            md += f"---\n\n*{tmpl['footer']}*\n"

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(md)

        logger.info(f"Exported Markdown: {filename}")
        return str(filepath)

    def export_to_text(self, data: dict) -> str:
        """Export report to plain text format."""
        EXPORTS_DIR.mkdir(parents=True, exist_ok=True)
        filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
        filepath = EXPORTS_DIR / filename

        text = "=" * 60 + "\n"
        text += "FORENSIC REPORT\n"
        text += "=" * 60 + "\n\n"
        text += f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"

        if "title" in data:
            text += f"Title: {data['title']}\n\n"

        if "summary" in data:
            text += "SUMMARY\n" + "-" * 40 + "\n"
            text += f"{data['summary']}\n\n"

        if "findings" in data and isinstance(data["findings"], list):
            text += "FINDINGS\n" + "-" * 40 + "\n"
            for i, finding in enumerate(data["findings"], 1):
                text += f"{i}. {finding}\n"
            text += "\n"

        if "metadata" in data and isinstance(data["metadata"], dict):
            text += "METADATA\n" + "-" * 40 + "\n"
            for key, value in data["metadata"].items():
                text += f"{key}: {value}\n"
            text += "\n"

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(text)

        logger.info(f"Exported Text: {filename}")
        return str(filepath)

    def list_exports(self) -> list[dict]:
        if not EXPORTS_DIR.exists():
            return []
        exports = []
        for f in EXPORTS_DIR.iterdir():
            if f.is_file():
                exports.append(
                    {
                        "filename": f.name,
                        "path": str(f),
                        "size": f.stat().st_size,
                        "created": datetime.fromtimestamp(f.stat().st_ctime).isoformat(),
                    }
                )
        return sorted(exports, key=lambda x: x["created"], reverse=True)


class ExportFormatsExtension(BasePlugin):
    def __init__(self, manifest: dict[str, Any], nexus_api: Any):
        super().__init__(manifest, nexus_api)
        self.formatter = ExportFormatter()

    async def on_startup(self):
        logger.info(f"[{self.plugin_id}] Export Formats extension activated")

    def get_tools(self):
        return [
            self.export_pdf,
            self.export_docx,
            self.export_html,
            self.export_markdown,
            self.export_text,
            self.list_exports,
        ]

    async def export_pdf(self, data: str, template: str = "default") -> str:
        """Export report to PDF."""
        try:
            data_dict = json.loads(data) if data else {}
        except json.JSONDecodeError:
            data_dict = {"raw": data}
        filepath = self.formatter.export_to_pdf(data_dict, template)
        return json.dumps({"format": "pdf", "filepath": filepath})

    async def export_docx(self, data: str, template: str = "default") -> str:
        """Export report to Word DOCX."""
        try:
            data_dict = json.loads(data) if data else {}
        except json.JSONDecodeError:
            data_dict = {"raw": data}
        filepath = self.formatter.export_to_docx(data_dict, template)
        return json.dumps({"format": "docx", "filepath": filepath})

    async def export_html(self, data: str, template: str = "default") -> str:
        """Export report to HTML."""
        try:
            data_dict = json.loads(data) if data else {}
        except json.JSONDecodeError:
            data_dict = {"raw": data}
        filepath = self.formatter.export_to_html(data_dict, template)
        return json.dumps({"format": "html", "filepath": filepath})

    async def export_markdown(self, data: str, template: str = "default") -> str:
        """Export report to Markdown."""
        try:
            data_dict = json.loads(data) if data else {}
        except json.JSONDecodeError:
            data_dict = {"raw": data}
        filepath = self.formatter.export_to_markdown(data_dict, template)
        return json.dumps({"format": "markdown", "filepath": filepath})

    async def export_text(self, data: str) -> str:
        """Export report to plain text."""
        try:
            data_dict = json.loads(data) if data else {}
        except json.JSONDecodeError:
            data_dict = {"raw": data}
        filepath = self.formatter.export_to_text(data_dict)
        return json.dumps({"format": "text", "filepath": filepath})

    async def list_exports(self) -> str:
        """List all exported files."""
        return json.dumps({"exports": self.formatter.list_exports()})


def register_extension(manifest: dict[str, Any], nexus_api: Any):
    return ExportFormatsExtension(manifest, nexus_api)
